CREATE TABLE IF NOT EXISTS users
(
    id      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance numeric(10, 2)
);

CREATE TABLE IF NOT EXISTS orders
(
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_service  int DEFAULT 0,
    id_user     int REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    amount      numeric(10, 2),
    description varchar(255),
    refill      boolean                   NOT NULL,
    order_time  timestamp DEFAULT current_timestamp
)